project:
  type: website
  render:
    - "*.qmd"
    - "!LICENSE.md"

format:
  html:
    theme: cyborg
    fontsize: 0.8em
  revealjs:
    footer: "{{< meta title >}} | <https://milanmlft.github.io/talks/>"
    hash-type: number
    history: false
    incremental: true
    link-external-icon: true
    link-external-newwindow: true
    slide-number: true
    theme: night

website:
  navbar:
    tools:
      - icon: house
        href: https://milanmlft.com
        target: _blank
      - icon: github
        href: https://github.com/milanmlft/talks
        target: _blank
  title: ""
  page-footer: 'This work is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">'
